application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      hlx-asset-addon-config:
        license: Apache-2.0
        actions:
          hlx-assets-addon-config:
            include:
              - ["node_modules/@minimatch"]
            function: actions/hlx-assets-addon-config/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
          ue-extn-config:
            include:
              - ["node_modules/@minimatch"]
            function: actions/ue-extn-config/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
          temp-config:
            function: actions/temp-config/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:18
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
